apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: krsrk/pokedex:v1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
          ports:
            - containerPort: 9000
