apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---

apiVersion: v1
kind: Service
metadata:
  name: app-dev-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
