apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: krsrk/pokedex:nginx1.25
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "16Mi"
          ports:
            - containerPort: 80
